# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_by_id_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import urllib.request
from PyQt5.QtWidgets import QDialog
from PyQt5.QtGui import QImage, QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
from db_manager import DBManager
from student_account import StudentAccount

# Search Student by ID Dialog
class Search_ID_Dialog(QDialog):
    # Constructor for Search_ID_Dialog object
    def __init__(self, parent=None):  # parent is sent during instantiation
        super(Search_ID_Dialog, self).__init__(parent)
        self.setup_ui(self)
        self.retranslate_ui(self)

    # Sets Search_ID_Dialog's attributes
    def setup_ui(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(695, 511)
        self.exit = QtWidgets.QPushButton(Dialog)
        self.exit.setGeometry(QtCore.QRect(500, 440, 113, 32))
        self.exit.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.exit.setObjectName("exit")
        self.exit.setAutoDefault(False)
        self.exit.clicked.connect(self.hide)
        self.search_by_id_label = QtWidgets.QLabel(Dialog)
        self.search_by_id_label.setGeometry(QtCore.QRect(0, 20, 711, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.search_by_id_label.setFont(font)
        self.search_by_id_label.setObjectName("search_by_id_label")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 50, 711, 10))
        self.line.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 410, 711, 10))
        self.line_2.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.first_name_label = QtWidgets.QLabel(Dialog)
        self.first_name_label.setGeometry(QtCore.QRect(270, 180, 101, 16))
        self.first_name_label.setObjectName("first_name_label")
        self.last_name_label = QtWidgets.QLabel(Dialog)
        self.last_name_label.setGeometry(QtCore.QRect(270, 210, 101, 16))
        self.last_name_label.setObjectName("last_name_label")
        self.email_label = QtWidgets.QLabel(Dialog)
        self.email_label.setGeometry(QtCore.QRect(270, 240, 60, 16))
        self.email_label.setObjectName("email_label")
        self.admit_year_label = QtWidgets.QLabel(Dialog)
        self.admit_year_label.setGeometry(QtCore.QRect(270, 270, 111, 16))
        self.admit_year_label.setObjectName("admit_year_label")
        self.photo_label = QtWidgets.QLabel(Dialog)
        self.photo_label.setGeometry(QtCore.QRect(270, 300, 60, 16))
        self.photo_label.setObjectName("photo_label")
        self.insert_photo = QtWidgets.QLabel(Dialog)
        self.insert_photo.setGeometry(QtCore.QRect(30, 160, 201, 181))
        self.insert_photo.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.insert_photo.setText("")
        self.insert_photo.setScaledContents(True)
        self.insert_photo.setObjectName("insert_photo")
        self.insert_first = QtWidgets.QLabel(Dialog)
        self.insert_first.setGeometry(QtCore.QRect(400, 180, 200, 20))
        self.insert_first.setStyleSheet("background-color:rgb(186, 216, 238)\n"
"")
        self.insert_first.setText("")
        self.insert_first.setObjectName("insert_first")
        self.insert_last = QtWidgets.QLabel(Dialog)
        self.insert_last.setGeometry(QtCore.QRect(400, 210, 200, 20))
        self.insert_last.setStyleSheet("background-color:rgb(186, 216, 238)\n"
"")
        self.insert_last.setText("")
        self.insert_last.setObjectName("insert_last")
        self.insert_email = QtWidgets.QLabel(Dialog)
        self.insert_email.setGeometry(QtCore.QRect(400, 240, 200, 20))
        self.insert_email.setStyleSheet("background-color:rgb(186, 216, 238)\n"
"")
        self.insert_email.setText("")
        self.insert_email.setObjectName("insert_email")
        self.insert_admit_year = QtWidgets.QLabel(Dialog)
        self.insert_admit_year.setGeometry(QtCore.QRect(400, 270, 200, 20))
        self.insert_admit_year.setStyleSheet("background-color:rgb(186, 216, 238)\n"
"")
        self.insert_admit_year.setText("")
        self.insert_admit_year.setObjectName("insert_admit_year")
        self.insert_photo_str = QtWidgets.QLabel(Dialog)
        self.insert_photo_str.setGeometry(QtCore.QRect(400, 300, 200, 20))
        self.insert_photo_str.setStyleSheet("background-color:rgb(186, 216, 238)\n"
"")
        self.insert_photo_str.setText("")
        self.insert_photo_str.setObjectName("insert_photo_str")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(80, 100, 501, 23))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.student_id_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.student_id_label.setFont(font)
        self.student_id_label.setObjectName("student_id_label")
        self.horizontalLayout.addWidget(self.student_id_label)
        spacerItem = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.lineEdit.returnPressed.connect(self.start_search)

        self.retranslate_ui(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # Translates attributes to user interface
    def retranslate_ui(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exit.setText(_translate("Dialog", "Exit"))
        self.search_by_id_label.setText(_translate("Dialog", "   Search By ID"))
        self.first_name_label.setText(_translate("Dialog", "First Name"))
        self.last_name_label.setText(_translate("Dialog", "Last Name"))
        self.email_label.setText(_translate("Dialog", "Email"))
        self.admit_year_label.setText(_translate("Dialog", "Admittance Year"))
        self.photo_label.setText(_translate("Dialog", "Photo"))
        self.student_id_label.setText(_translate("Dialog", "Student ID"))

    # Retrieves student ID (input from user) and searches the database for the ID
    def start_search(self):
        user_id = self.lineEdit.text()
        db_manager = DBManager()
        record = db_manager.search_by_id(user_id)
        if record is None:
            return
        self.display_record(record)

    # Displays student record on user interface
    def display_record(self, record):
        self.insert_first.setText(record[1])
        self.insert_last.setText(record[2])
        self.insert_email.setText(record[3])
        self.insert_admit_year.setText(str(record[4]))
        self.insert_photo_str.setText(record[5])

        link = "http://cse2050.drfitz.fit/data/avatars/" + record[5]
        self.load_image(link)

    # Loads image from link and displays the resulting pixmap
    def load_image(self, link):
        img = QImage()
        img.loadFromData(self.read_img(link))

        pixmap = QPixmap.fromImage(img)
        scaled_img = pixmap.scaled(100, 100, QtCore.Qt.KeepAspectRatio)
        self.insert_photo.setPixmap(scaled_img)

    # Retrieves the image's bytes from a link
    def read_img(self, link):
        img_bytes = urllib.request.urlopen(link).read()
        return img_bytes

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Search_ID_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
