# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_by_name_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QDialog, QScrollArea, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets
from db_manager import DBManager

# Search Student By Name Dialog
class Search_Name_Dialog(QDialog):
    # Constructor for Search_Name_Dialog object
    def __init__(self, parent=None):  # parent is sent during instantiation
        super(Search_Name_Dialog, self).__init__(parent)
        self.setup_ui(self)
        self.retranslate_ui(self)

    # Sets up Search_Name_Dialog's attributes
    def setup_ui(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 530)
        self.search_by_name_label = QtWidgets.QLabel(Dialog)
        self.search_by_name_label.setGeometry(QtCore.QRect(-1, 5, 751, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.search_by_name_label.setFont(font)
        self.search_by_name_label.setObjectName("search_by_name_label")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 40, 711, 10))
        self.line.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 390, 711, 10))
        self.line_2.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 70, 501, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.student_name_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.student_name_label.setFont(font)
        self.student_name_label.setObjectName("student_name_label")
        self.horizontalLayout.addWidget(self.student_name_label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.lineEdit.returnPressed.connect(self.start_search)
        self.exit_button = QtWidgets.QPushButton(Dialog)
        self.exit_button.setGeometry(QtCore.QRect(400, 430, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.exit_button.setObjectName("exit_button")
        self.exit_button.setAutoDefault(False)
        self.exit_button.clicked.connect(self.hide)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 100, 601, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 581, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setColumnWidth(0, 100)
        self.tableWidget.setColumnWidth(1,100)
        self.tableWidget.setColumnWidth(2,100)
        self.tableWidget.setColumnWidth(3,200)
        self.tableWidget.setColumnWidth(4,90)
        self.tableWidget.setColumnWidth(5,250)
        self.tableWidget.setHorizontalHeaderLabels(["Student ID", "First Name", "Last Name", "Email","Admittance Year", "Photo"])

        self.retranslate_ui(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # Translates Search_Name_Dialog's attributes to user interface
    def retranslate_ui(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.search_by_name_label.setText(_translate("Dialog", "   Search By Name"))
        self.student_name_label.setText(_translate("Dialog", "Student Name"))
        self.exit_button.setText(_translate("Dialog", "Exit"))

    # Retrieves user input as string and search's database for students' records
    def start_search(self):
        name = self.lineEdit.text()
        db_manager = DBManager()
        records = db_manager.search_by_name(name)
        if records is None:
            return
        self.display_records(records)

    # Displays students' records in tableWidget
    def display_records(self, records):
        num_rows = len(records)
        self.tableWidget.setRowCount(num_rows)
        table_row = 0
        for row in records:
            self.tableWidget.setItem(table_row, 0, QtWidgets.QTableWidgetItem(str(row[0])))
            self.tableWidget.setItem(table_row, 1, QtWidgets.QTableWidgetItem(row[1]))
            self.tableWidget.setItem(table_row, 2, QtWidgets.QTableWidgetItem(row[2]))
            self.tableWidget.setItem(table_row, 3, QtWidgets.QTableWidgetItem(row[3]))
            self.tableWidget.setItem(table_row, 4, QtWidgets.QTableWidgetItem(str(row[4])))
            self.tableWidget.setItem(table_row, 5, QtWidgets.QTableWidgetItem(row[5]))
            table_row += 1

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Search_Name_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
