# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thank_you_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import urllib.request
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QDialog

# Thank You Dialog
class Thank_You_Dialog(QDialog):
    # Constructs instance of Thank_You_Dialog
    def __init__(self, parent=None):  # parent is sent during instantiation
        super(Thank_You_Dialog, self).__init__(parent)
        self._curr_index = 0
        self._memes = ["https://pics.me.me/thumb_python-programming-71361704.png","https://i.pinimg.com/564x/da/ff/d0/daffd0d1d3acae0297314dc01ab2641b.jpg",
                       "https://qph.fs.quoracdn.net/main-qimg-7a0cc19a817c161f643497eabf369b7f", "https://qph.fs.quoracdn.net/main-qimg-3ad44e4e9b16cce7e941756d49eba556",
                       "https://ahseeit.com//king-include/uploads/2021/02/thumb_60258de914219-3915971752.jpeg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgM4RjmypqD9sDdiacg1fUi5Mup7eB4Sz8Ug&usqp=CAU",
                        "https://i.pinimg.com/236x/9a/61/71/9a6171cbd400dc605a002569d050c168.jpg", "https://i.pinimg.com/736x/28/0f/e5/280fe5e6d8725b9a110cee1f20846ced.jpg",
                       "https://i.redd.it/isyu86r7sor21.png", "https://i.imgur.com/A7YZt1Z.jpg", "https://www.codeitbro.com/wp-content/uploads/2020/07/python-jokes-delete-block-of-code.jpg",
                       "https://i.pinimg.com/originals/c6/4e/fc/c64efc9adaedbf446f328698e8b67388.jpg"]
        self.setup_ui(self)
        self.retranslate_ui(self)

    # Sets up Thank_You_Dialog's attributes
    def setup_ui(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(709, 532)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 50, 711, 10))
        self.line.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.picture_label = QtWidgets.QLabel(Dialog)
        self.picture_label.setGeometry(QtCore.QRect(10, 80, 681, 331))
        self.picture_label.setObjectName("picture_label")
        self.picture_label.setAlignment(QtCore.Qt.AlignCenter)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 440, 711, 10))
        self.line_2.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(420, 470, 191, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.next_button = QtWidgets.QPushButton(self.widget)
        self.next_button.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.next_button.clicked.connect(self.next_image)
        self.exit_button = QtWidgets.QPushButton(self.widget)
        self.exit_button.setStyleSheet("background-color:rgb(186, 216, 238)")
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        self.exit_button.clicked.connect(self.hide)
        self.retranslate_ui(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # Translates Thank_You_Dialog's attributes to user interface
    def retranslate_ui(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Thank you Dr. Fitz and the rest of CSE 2050 staff for a great semester!"))
        self.picture_label.setText(_translate("Dialog", "Click next!"))
        self.next_button.setText(_translate("Dialog", "Next"))
        self.exit_button.setText(_translate("Dialog", "Exit"))

    # Displays next image from link in memes
    def next_image(self):
        if self._curr_index >= len(self._memes) :
            self._curr_index = 0
        pixmap = self.load_image(self._memes[self._curr_index])
        self.picture_label.setPixmap(pixmap)
        self._curr_index += 1

    # Returns a pixmap from an image from a link
    def load_image(self, link):
        img = QImage()
        img.loadFromData(self.read_img(link))

        pixmap = QPixmap.fromImage(img)
        scaled_img = pixmap.scaled(681, 331, QtCore.Qt.KeepAspectRatio)
        return scaled_img

    # Returns an image's bytes from a link
    def read_img(self, link):
        img_bytes = urllib.request.urlopen(link).read()
        return img_bytes

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Thank_You_Dialog()
    ui.setup_ui(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
